spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: ${DB_URL}
    username: ${USER_DB}
    password: ${PASSWORD_DB}
  jpa:
    show-sql: true
security:
  jwt:
    key:
      private: ${JWT_KEY}
    user:
      generator: ${JWT_USER_GENERATOR}
  cors:
    allowed-origins: ${ORIGINS_CORS}
server:
  port: 8080
